ALTER TABLE work_order_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE work_order_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE work_order_timeline DISABLE ROW LEVEL SECURITY;
ALTER TABLE work_order_photos DISABLE ROW LEVEL SECURITY;
