-- Mobile service columns on work_orders
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS mobile_service_type TEXT DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS mobile_status TEXT DEFAULT 'scheduled';
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS mobile_address TEXT DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS mobile_km NUMERIC(8,2) DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS travel_cost NUMERIC(10,2) DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS travel_cost_charged BOOLEAN DEFAULT true;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS travel_minutes INTEGER DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS technician_name TEXT DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS fuel_cost NUMERIC(10,2) DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS customer_signature TEXT DEFAULT NULL;

-- Tire service details
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS tire_size TEXT DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS tire_dot TEXT DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS tire_tread_depth NUMERIC(4,2) DEFAULT NULL;
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS tire_pressure NUMERIC(5,2) DEFAULT NULL;

-- VIP on customers
ALTER TABLE customers ADD COLUMN IF NOT EXISTS is_vip BOOLEAN DEFAULT false;
